sudo: required
dist: trusty
language: node_js
node_js:
- '9'
install:
- npm install
- npm install codecov -g
script:
- npm run build
- npm run test
- npm run coverage
deploy:
  provider: npm
  email: npm@outrunlabs.com
  skip_cleanup: true
  api_key:
    secure: YsWWEhHI3Gs64dBeVoeBhtWNDaQkJ3pV9o5O9nNW7v+Rfcru72uP9vY49OTSduAMBg5OaXmNpH/tShO3cAEg66cuZOCLx7tizCV4aarzu1ObhCfLRCBzMj0rhcLW3gxo0r1Af1zhr4J6dAUWXKOdbFX533wKpJXgs5tmToGrVvYb0j4t0nlegStBsjfTloRoTr1RJtrFGrpN75NcvGGGAz6iYY37fXqhD1u9LkDeC4w3F7GtnUQcLQiFbqa7YZK4MA8SFb/tUjOeIdatj7O+zBa7djqMEIWPVEP8tg7YSrA/d0/xPHIN0LjAeP7EbEx6ttTNgbnc6ZB+xrP3xJe16/fafxnKrmbEUnUqGjx3R3hFmEm7OTLe/pAfk0rM0FNw2VGsaIKbP93cLTcQEGjcP0SJ+CdSsLLMGTCFU0zho9WtorBI9RtbSMBTzYo1BFNVQ71S9S9lQEurM+o7xpgoWqOLSQnpZ+DiNHtkP9eNArJXop7nLqF51PATet49TXL6ucaz6F23raOUxxtlkJuWgNaxLnR5a7Tuog/bAA1v/23s7Irrbg/iclZMI8vP66EDQAzz7P3BQ7qI84Q4aWXQSzhwDB19zldrsxLIdgpoSurK9C8wIZ3J1WWwzLZnTObfbeP4tagOkv+teFDrKS8hFa7tsl6hYO44FpmZd2CTjKU=
  on:
    repo: outrunlabs/outrun-renderer-3d
